### ISSUE TITLE
template rendered runs before snap is loaded

### ISSUE THREAD

**Issue by mattybow** [mirageglobe/meteorsnapsvgcdn#1]
I'm using Meteor 1.0 and in my `Template.name.rendered` function, I'm using Snap.svg, however on page load I get this error.

```
Exception from Tracker afterFlush function: Snap is not defined
ReferenceError: Snap is not defined
```

When I look at the inspector network timeline, I see that Snap.svg is taking a while to load.  
![screen shot 2014-11-25 at 1 01 13 pm](https://cloud.githubusercontent.com/assets/4393087/5189444/98334366-74a3-11e4-8162-349c857d699b.png)

Have you run into this problem?  If so, is there a solution?  Do I need to use IRLibLoad (meteor add manuelschoebel:wait-on-lib)

**Comment by mirageglobe** [comment]
Strange. I didn't encounter this problem. let me have a look.

**Comment by mirageglobe** [comment]
Hi matty.. try ... the following. it tests the snap before aborting. Alternatively if you tried the wait-on-lib. let me know if it works?... the following does not use anything else and just works fine here..

// snapsvgdraw is a template with nothing in it. this draws a 800 x 600 canvas for drawing.
Template.snapsvgdraw.rendered = function () {
    "use strict";

```
Meteor.setTimeout(function () {var s = new Snap(800, 600), bigCircle = s.circle(150, 150, 100); }, 1000);
```

  };

![screen shot 2014-12-01 at 22 31 21](https://cloud.githubusercontent.com/assets/577792/5254617/fcfa372c-79a9-11e4-9210-8394810ab4c5.png)
